Summary: Micro-framework in PHP 5.4 wich uses top features provides by this stuff
Name: donnie
Version: 0.1
Release: 1
License: GPL
Group: Utilities/System
#Source: github.com/nergal/donnie/tarball/master
#Source: ./src/
%description
Micro-framework in PHP 5.4 wich uses top features provides by this stuff

%prep
%setup

%build
maven rpm

%install
install -s -m 755 -o 0 -g 0 eject /usr/bin/eject
install -m 644 -o 0 -g 0 eject.1 /usr/man/man1

%files
%doc README.md COPYING.md ChangeLog.md

public/index.php
public/images/favicon.ico
public/js/jquery-1.6.4.min.js
public/js/html5.js
public/css/bootstrap.min.css
core/init.php
core/view.php
core/vendor/twig/LICENSE
core/vendor/twig/phpunit.xml.dist
core/vendor/twig/README.markdown
core/vendor/twig/doc/extensions.rst
core/vendor/twig/doc/api.rst
core/vendor/twig/doc/tags/autoescape.rst
core/vendor/twig/doc/tags/extends.rst
core/vendor/twig/doc/tags/raw.rst
core/vendor/twig/doc/tags/include.rst
core/vendor/twig/doc/tags/for.rst
core/vendor/twig/doc/tags/spaceless.rst
core/vendor/twig/doc/tags/filter.rst
core/vendor/twig/doc/tags/index.rst
core/vendor/twig/doc/tags/set.rst
core/vendor/twig/doc/tags/if.rst
core/vendor/twig/doc/tags/from.rst
core/vendor/twig/doc/tags/macro.rst
core/vendor/twig/doc/tags/import.rst
core/vendor/twig/doc/tags/use.rst
core/vendor/twig/doc/tags/block.rst
core/vendor/twig/doc/hacking.rst
core/vendor/twig/doc/tests/empty.rst
core/vendor/twig/doc/tests/divisibleby.rst
core/vendor/twig/doc/tests/even.rst
core/vendor/twig/doc/tests/sameas.rst
core/vendor/twig/doc/tests/defined.rst
core/vendor/twig/doc/tests/index.rst
core/vendor/twig/doc/tests/odd.rst
core/vendor/twig/doc/tests/none.rst
core/vendor/twig/doc/tests/constant.rst
core/vendor/twig/doc/index.rst
core/vendor/twig/doc/templates.rst
core/vendor/twig/doc/recipes.rst
core/vendor/twig/doc/advanced.rst
core/vendor/twig/doc/filters/join.rst
core/vendor/twig/doc/filters/lower.rst
core/vendor/twig/doc/filters/upper.rst
core/vendor/twig/doc/filters/title.rst
core/vendor/twig/doc/filters/raw.rst
core/vendor/twig/doc/filters/default.rst
core/vendor/twig/doc/filters/index.rst
core/vendor/twig/doc/filters/url_encode.rst
core/vendor/twig/doc/filters/replace.rst
core/vendor/twig/doc/filters/striptags.rst
core/vendor/twig/doc/filters/capitalize.rst
core/vendor/twig/doc/filters/reverse.rst
core/vendor/twig/doc/filters/escape.rst
core/vendor/twig/doc/filters/json_encode.rst
core/vendor/twig/doc/filters/keys.rst
core/vendor/twig/doc/filters/merge.rst
core/vendor/twig/doc/filters/sort.rst
core/vendor/twig/doc/filters/length.rst
core/vendor/twig/doc/filters/format.rst
core/vendor/twig/doc/filters/date.rst
core/vendor/twig/doc/intro.rst
core/vendor/twig/doc/functions/range.rst
core/vendor/twig/doc/functions/cycle.rst
core/vendor/twig/doc/functions/index.rst
core/vendor/twig/doc/functions/parent.rst
core/vendor/twig/doc/functions/attribute.rst
core/vendor/twig/doc/functions/constant.rst
core/vendor/twig/doc/functions/block.rst
core/vendor/twig/package.xml.tpl
core/vendor/twig/bin/create_pear_package.php
core/vendor/twig/AUTHORS
core/vendor/twig/test/bootstrap.php
core/vendor/twig/test/Twig/Tests/ParserTest.php
core/vendor/twig/test/Twig/Tests/ErrorTest.php
core/vendor/twig/test/Twig/Tests/Loader/ArrayTest.php
core/vendor/twig/test/Twig/Tests/Loader/ChainTest.php
core/vendor/twig/test/Twig/Tests/Loader/FilesystemTest.php
core/vendor/twig/test/Twig/Tests/NodeVisitor/OptimizerTest.php
core/vendor/twig/test/Twig/Tests/TemplateTest.php
core/vendor/twig/test/Twig/Tests/FileCachingTest.php
core/vendor/twig/test/Twig/Tests/Fixtures/exceptions/unclosed_tag.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/values.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/else.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/keys_and_values.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/inner_variables.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/nested_else.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/context.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/loop_context_local.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/loop_context.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/recursive.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/objects.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/objects_countable.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/for/keys.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/type.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/double_escaping.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/raw.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/with_pre_escape_filters.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/strategy.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/functions.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/blocks.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/with_filters_arguments.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/with_filters.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/literal.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/nested.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/autoescape/objects.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/special_chars.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/raw/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/expression.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/only.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/ignore_missing.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/template_instance.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/templates_as_array.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/include/with_variables.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/block/special_chars.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/block/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/use/multiple_aliases.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/use/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/use/multiple.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/use/deep_empty.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/use/aliases.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/use/deep.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/spaceless/simple.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/macro/special_chars.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/macro/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/macro/self_import.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/macro/endmacro_name.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/macro/external.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/macro/from.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/set/expression.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/set/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/set/capture.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/trim_block.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/filter/with_for_tag.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/filter/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/filter/multiple.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/filter/nested.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/filter/json_encode.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/filter/with_if_tag.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/conditional.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/nested_inheritance.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/multiple.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/dynamic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent_nested.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent_change.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent_in_a_block.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent_without_extends.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent_isolation.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/use.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/template_instance.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/parent_without_extends_but_traits.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/inheritance/extends_as_array.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/from.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/if/expression.test
core/vendor/twig/test/Twig/Tests/Fixtures/tags/if/basic.test
core/vendor/twig/test/Twig/Tests/Fixtures/tests/odd.test
core/vendor/twig/test/Twig/Tests/Fixtures/tests/constant.test
core/vendor/twig/test/Twig/Tests/Fixtures/tests/array.test
core/vendor/twig/test/Twig/Tests/Fixtures/tests/empty.test
core/vendor/twig/test/Twig/Tests/Fixtures/tests/even.test
core/vendor/twig/test/Twig/Tests/Fixtures/tests/defined.test
core/vendor/twig/test/Twig/Tests/Fixtures/regression/empty_token.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/special_chars.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/force_escape.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/sort.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/format.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/length.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/date.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/default.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/merge.test
core/vendor/twig/test/Twig/Tests/Fixtures/filters/json_encode.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/magic_call.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/method_call.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/array.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/binary.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/dotdot.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/ternary_operator.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/postfix.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/grouping.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/array_call.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/unary.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/literals.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/in.test
core/vendor/twig/test/Twig/Tests/Fixtures/expressions/comparison.test
core/vendor/twig/test/Twig/Tests/Fixtures/functions/special_chars.test
core/vendor/twig/test/Twig/Tests/Fixtures/functions/constant.test
core/vendor/twig/test/Twig/Tests/Fixtures/functions/cycle.test
core/vendor/twig/test/Twig/Tests/Fixtures/functions/attribute.test
core/vendor/twig/test/Twig/Tests/AutoloaderTest.php
core/vendor/twig/test/Twig/Tests/Node/ModuleTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/ArrayTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/NameTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Unary/PosTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Unary/NegTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Unary/NotTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/ConditionalTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/FilterTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/FloorDivTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/OrTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/SubTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/ConcatTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/AddTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/MulTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/DivTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/AndTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/Binary/ModTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/AssignNameTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/ConstantTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/ParentTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/GetAttrTest.php
core/vendor/twig/test/Twig/Tests/Node/Expression/FunctionTest.php
core/vendor/twig/test/Twig/Tests/Node/BlockTest.php
core/vendor/twig/test/Twig/Tests/Node/SandboxTest.php
core/vendor/twig/test/Twig/Tests/Node/AutoEscapeTest.php
core/vendor/twig/test/Twig/Tests/Node/SpacelessTest.php
core/vendor/twig/test/Twig/Tests/Node/ImportTest.php
core/vendor/twig/test/Twig/Tests/Node/PrintTest.php
core/vendor/twig/test/Twig/Tests/Node/BlockReferenceTest.php
core/vendor/twig/test/Twig/Tests/Node/TextTest.php
core/vendor/twig/test/Twig/Tests/Node/SandboxedPrintTest.php
core/vendor/twig/test/Twig/Tests/Node/ForTest.php
core/vendor/twig/test/Twig/Tests/Node/IfTest.php
core/vendor/twig/test/Twig/Tests/Node/TestCase.php
core/vendor/twig/test/Twig/Tests/Node/SandboxedModuleTest.php
core/vendor/twig/test/Twig/Tests/Node/IncludeTest.php
core/vendor/twig/test/Twig/Tests/Node/SetTest.php
core/vendor/twig/test/Twig/Tests/Node/MacroTest.php
core/vendor/twig/test/Twig/Tests/LexerTest.php
core/vendor/twig/test/Twig/Tests/integrationTest.php
core/vendor/twig/test/Twig/Tests/TestCase.php
core/vendor/twig/test/Twig/Tests/TokenStreamTest.php
core/vendor/twig/test/Twig/Tests/ExpressionParserTest.php
core/vendor/twig/test/Twig/Tests/Extension/SandboxTest.php
core/vendor/twig/CHANGELOG
core/vendor/twig/lib/Twig/FunctionInterface.php
core/vendor/twig/lib/Twig/TokenParserBrokerInterface.php
core/vendor/twig/lib/Twig/ExtensionInterface.php
core/vendor/twig/lib/Twig/Function.php
core/vendor/twig/lib/Twig/Node.php
core/vendor/twig/lib/Twig/Markup.php
core/vendor/twig/lib/Twig/Sandbox/SecurityError.php
core/vendor/twig/lib/Twig/Sandbox/SecurityPolicy.php
core/vendor/twig/lib/Twig/Sandbox/SecurityPolicyInterface.php
core/vendor/twig/lib/Twig/Lexer.php
core/vendor/twig/lib/Twig/Filter/Function.php
core/vendor/twig/lib/Twig/Filter/Method.php
core/vendor/twig/lib/Twig/TokenStream.php
core/vendor/twig/lib/Twig/Test/Function.php
core/vendor/twig/lib/Twig/Test/Method.php
core/vendor/twig/lib/Twig/Loader/Filesystem.php
core/vendor/twig/lib/Twig/Loader/Chain.php
core/vendor/twig/lib/Twig/Loader/String.php
core/vendor/twig/lib/Twig/Loader/Array.php
core/vendor/twig/lib/Twig/Error.php
core/vendor/twig/lib/Twig/Environment.php
core/vendor/twig/lib/Twig/NodeVisitor/Escaper.php
core/vendor/twig/lib/Twig/NodeVisitor/Optimizer.php
core/vendor/twig/lib/Twig/NodeVisitor/Sandbox.php
core/vendor/twig/lib/Twig/NodeVisitor/SafeAnalysis.php
core/vendor/twig/lib/Twig/TestInterface.php
core/vendor/twig/lib/Twig/TemplateInterface.php
core/vendor/twig/lib/Twig/LoaderInterface.php
core/vendor/twig/lib/Twig/FilterInterface.php
core/vendor/twig/lib/Twig/TokenParser/Extends.php
core/vendor/twig/lib/Twig/TokenParser/From.php
core/vendor/twig/lib/Twig/TokenParser/Macro.php
core/vendor/twig/lib/Twig/TokenParser/Block.php
core/vendor/twig/lib/Twig/TokenParser/AutoEscape.php
core/vendor/twig/lib/Twig/TokenParser/Use.php
core/vendor/twig/lib/Twig/TokenParser/Sandbox.php
core/vendor/twig/lib/Twig/TokenParser/Filter.php
core/vendor/twig/lib/Twig/TokenParser/Set.php
core/vendor/twig/lib/Twig/TokenParser/For.php
core/vendor/twig/lib/Twig/TokenParser/Include.php
core/vendor/twig/lib/Twig/TokenParser/Spaceless.php
core/vendor/twig/lib/Twig/TokenParser/Import.php
core/vendor/twig/lib/Twig/TokenParser/If.php
core/vendor/twig/lib/Twig/TokenParserInterface.php
core/vendor/twig/lib/Twig/Node/Text.php
core/vendor/twig/lib/Twig/Node/Expression/Test.php
core/vendor/twig/lib/Twig/Node/Expression/Unary/Pos.php
core/vendor/twig/lib/Twig/Node/Expression/Unary/Neg.php
core/vendor/twig/lib/Twig/Node/Expression/Unary/Not.php
core/vendor/twig/lib/Twig/Node/Expression/Function.php
core/vendor/twig/lib/Twig/Node/Expression/Parent.php
core/vendor/twig/lib/Twig/Node/Expression/BlockReference.php
core/vendor/twig/lib/Twig/Node/Expression/Constant.php
core/vendor/twig/lib/Twig/Node/Expression/GetAttr.php
core/vendor/twig/lib/Twig/Node/Expression/ExtensionReference.php
core/vendor/twig/lib/Twig/Node/Expression/Array.php
core/vendor/twig/lib/Twig/Node/Expression/Filter.php
core/vendor/twig/lib/Twig/Node/Expression/Name.php
core/vendor/twig/lib/Twig/Node/Expression/AssignName.php
core/vendor/twig/lib/Twig/Node/Expression/Conditional.php
core/vendor/twig/lib/Twig/Node/Expression/Binary.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Mul.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Equal.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Range.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Power.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Greater.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Less.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Add.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Sub.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Concat.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/BitwiseAnd.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/And.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Div.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/BitwiseOr.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Or.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/BitwiseXor.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/In.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/Mod.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/LessEqual.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/NotIn.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/GreaterEqual.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/NotEqual.php
core/vendor/twig/lib/Twig/Node/Expression/Binary/FloorDiv.php
core/vendor/twig/lib/Twig/Node/Expression/Unary.php
core/vendor/twig/lib/Twig/Node/SandboxedPrint.php
core/vendor/twig/lib/Twig/Node/Macro.php
core/vendor/twig/lib/Twig/Node/BlockReference.php
core/vendor/twig/lib/Twig/Node/Block.php
core/vendor/twig/lib/Twig/Node/AutoEscape.php
core/vendor/twig/lib/Twig/Node/Print.php
core/vendor/twig/lib/Twig/Node/Module.php
core/vendor/twig/lib/Twig/Node/Sandbox.php
core/vendor/twig/lib/Twig/Node/Set.php
core/vendor/twig/lib/Twig/Node/For.php
core/vendor/twig/lib/Twig/Node/Expression.php
core/vendor/twig/lib/Twig/Node/Include.php
core/vendor/twig/lib/Twig/Node/Spaceless.php
core/vendor/twig/lib/Twig/Node/SandboxedModule.php
core/vendor/twig/lib/Twig/Node/Import.php
core/vendor/twig/lib/Twig/Node/If.php
core/vendor/twig/lib/Twig/NodeInterface.php
core/vendor/twig/lib/Twig/Template.php
core/vendor/twig/lib/Twig/ExpressionParser.php
core/vendor/twig/lib/Twig/Filter.php
core/vendor/twig/lib/Twig/NodeOutputInterface.php
core/vendor/twig/lib/Twig/Token.php
core/vendor/twig/lib/Twig/Extension.php
core/vendor/twig/lib/Twig/NodeTraverser.php
core/vendor/twig/lib/Twig/ParserInterface.php
core/vendor/twig/lib/Twig/LexerInterface.php
core/vendor/twig/lib/Twig/CompilerInterface.php
core/vendor/twig/lib/Twig/Parser.php
core/vendor/twig/lib/Twig/NodeVisitorInterface.php
core/vendor/twig/lib/Twig/TokenParserBroker.php
core/vendor/twig/lib/Twig/Error/Loader.php
core/vendor/twig/lib/Twig/Error/Syntax.php
core/vendor/twig/lib/Twig/Error/Runtime.php
core/vendor/twig/lib/Twig/Function/Function.php
core/vendor/twig/lib/Twig/Function/Method.php
core/vendor/twig/lib/Twig/Autoloader.php
core/vendor/twig/lib/Twig/Extension/Escaper.php
core/vendor/twig/lib/Twig/Extension/Optimizer.php
core/vendor/twig/lib/Twig/Extension/Sandbox.php
core/vendor/twig/lib/Twig/Extension/Core.php
core/vendor/twig/lib/Twig/Compiler.php
core/vendor/twig/lib/Twig/TokenParser.php
core/controller.php
core/router.php
core/template/twig.php
core/template/php.php
core/loader.php
core/singleton.php
core/template.php
core/pimple.php
application/controller/main.php
application/cache/includes.conf
application/templates/index.php
application/templates/layout.php
application/routing.php
README.md
